export const languages = {
    portuguese: {
        confirmBtn: "Confirmar",
        cancelBtn: "Cancelar",
        siderProfileBtn: "Perfil",
        generateBtn: "Gerar",
        siderLaboratoryBtn: "Laboratório",
        usernameInput: "Usuário",
        nameInput: "Nome",
        passwordInput: "Senha",
        descriptionInput: "Descrição",
        musicLabel: "Música",
        musicsLabel: "Músicas",
        profile: {
            editModalTitle: "Edite seu perfil:",
            editRoleTitle: "Edite suas funções:",
            emptyRoleTitle: "Sem funções atribuídas." 
        },
        laboratory: {
            chooseMethodTitle: "Descubra novas músicas de diferentes formas:",
            randomMethod: "Aleatório",
            randomMethodTitle: "Crie uma playlist aleatória!",
            calendarMethod: "Calendário",
            musicPlaylistView: "Músicas",
            customMethod: "Personalizado",
            paramPlaylistView: "Parâmetros",
            playlistNamePlaceholder: "Digite um nome para sua playlist",
            exportToSpotifyBtn: "Salve no Spotify",
            savedOnSpotifyBtn: "Playlist salva",
            emptyPlaylistTitle: "Nenhuma playlist criada.",
            params: {
                genres: 'Gêneros',
                danceability: "Dançabilidade",
                energy: "Energia",
                acousticness: "Acusticidade",
                instrumentalness: "Instrumentalidade",
                happiness: "Felicidade",
                popularity: "Popularidade"
            }
        },
        roles: {
            DRUMMER: "Baterista",
            GUITARIST: "Guitarrista",
            BASSIST: "Baixista",
            SINGER: "Cantor",
            KEYBOARD_PLAYER: "Tecladista",
            SAXOPHONIST: "Saxofonista",
            VIOLINIST: "Violinista",
            SONGWRITER: "Compositor",
            TRUMPET_PLAYER: "Trompetista",
            DJ: "DJ",
            AUDIO_ENGINEER: "Engenheiro de Som",
            MUSIC_TEACHER: "Professor de Música",
            VOCAL_COACH: "Treinador Vocal",
            LISTENER: "Ouvinte",
            JOURNALIST: "Jornalista",
            INFLUENCER: "Influenciador",
            HOST: "Anfitrião",
            MANAGER: "Empresário",
            ROADIE: "Roadie",
            PIANIST: "Pianista",
            INSTRUMENTALIST: "Instrumentista",
            MUSICIAN: "Músico",
            MUSIC_PRODUCER: "Produtor Musical",
            EVENT_PRODUCER: "Produtor de Eventos"
        },
        genres: {
            POP: "Pop",
            ROCK: "Rock",
            JAZZ: "Jazz",
            CLASSICAL: "Clássico",
            HIP_HOP: "Hip-Hop",
            COUNTRY: "Country",
            BLUES: "Blues",
            REGGAE: "Reggae",
            ELECTRONIC: "Eletrônica",
            FOLK: "Folk",
            SOUL: "Soul",
            METAL: "Metal",
            DISCO: "Disco",
            FUNK: "Funk",
            INDIE: "Indie",
            PUNK: "Punk",
            BOSSANOVA: "Bossa Nova",
            SAMBA: "Samba",
            SERTANEJO: "Sertanejo",
            FORRO: "Forró",
            SALSA: "Salsa",
            SKA: "Ska",
            GRUNGE: "Grunge",
            MPB: "MPB",
            PAGODE: "Pagode"
        }
    }
}