export const languages = {
    portuguese: {
        confirmBtn: "Confirmar",
        cancelBtn: "Cancelar",
        siderProfileBtn: "Perfil",
        generateBtn: "Gerar",
        siderLaboratoryBtn: "Laboratório",
        usernameInput: "Usuário",
        nameInput: "Nome",
        passwordInput: "Senha",
        descriptionInput: "Descrição",
        profile: {
            editModalTitle: "Edite seu perfil:",
            editRoleTitle: "Edite suas funções:",
            emptyRoleTitle: "Sem funções atribuídas." 
        },
        laboratory: {
            chooseMethodTitle: "Descubra novas músicas de diferentes formas:",
            randomMethod: "Aleatório",
            randomMethodTitle: "Crie uma playlist aleatória!",
            calendarMethod: "Calendário",
            musicPlaylistView: "Músicas",
            paramPlaylistView: "Parâmetros",
            playlistNamePlaceholder: "Digite um nome para sua playlist",
            params: {
                genres: 'Gêneros',
                danceability: "Dançabilidade",
                energy: "Energia",
                acousticness: "Acusticidade",
                instrumentalness: "Instrumentalidade",
                loudness: "Volume",
                happiness: "Felicidade"
            }
        },
        roles: {
            DRUMMER: "Baterista",
            GUITARIST: "Guitarrista",
            BASSIST: "Baixista",
            SINGER: "Cantor",
            KEYBOARD_PLAYER: "Tecladista",
            SAXOPHONIST: "Saxofonista",
            VIOLINIST: "Violinista",
            SONGWRITER: "Compositor",
            TRUMPET_PLAYER: "Trompetista",
            DJ: "DJ",
            AUDIO_ENGINEER: "Engenheiro de Som",
            MUSIC_TEACHER: "Professor de Música",
            VOCAL_COACH: "Treinador Vocal",
            LISTENER: "Ouvinte",
            JOURNALIST: "Jornalista",
            INFLUENCER: "Influenciador",
            HOST: "Anfitrião",
            MANAGER: "Empresário",
            ROADIE: "Roadie",
            PIANIST: "Pianista",
            INSTRUMENTALIST: "Instrumentista",
            MUSICIAN: "Músico",
            MUSIC_PRODUCER: "Produtor Musical",
            EVENT_PRODUCER: "Produtor de Eventos"
        },
        genres: {
            pop: "Pop",
            rock: "Rock",
            jazz: "Jazz",
            classical: "Clássico",
            hipHop: "Hip-Hop",
            country: "Country",
            blues: "Blues",
            reggae: "Reggae",
            electronic: "Eletrônica",
            folk: "Folk",
            soul: "Soul",
            metal: "Metal",
            disco: "Disco",
            funk: "Funk",
            indie: "Indie",
            punk: "Punk",
            bossanova: "Bossa Nova",
            samba: "Samba",
            sertanejo: "Sertanejo",
            forro: "Forró",
            salsa: "Salsa",
            ska: "Ska",
            grunge: "Grunge",
            mpb: "MPB",
            pagode: "Pagode"
        }
    }
}